import paramiko
import time

client1 = paramiko.SSHClient()
client1.set_missing_host_key_policy(paramiko.WarningPolicy())
client1.set_missing_host_key_policy(paramiko.AutoAddPolicy())
client2 = paramiko.SSHClient()
client2.set_missing_host_key_policy(paramiko.WarningPolicy())
client2.set_missing_host_key_policy(paramiko.AutoAddPolicy())
#client3 = paramiko.SSHClient()
#client3.set_missing_host_key_policy(paramiko.WarningPolicy())
#client3.set_missing_host_key_policy(paramiko.AutoAddPolicy())
time.sleep(1)
client1.connect("192.168.137.2", username='pi', password="Matale_1")
client2.connect("192.168.137.4", username='pi', password="Matale_1") # change back to 3 ---------------------
#client3.connect("192.168.137.4", username='pi', password="Matale_1")
time.sleep(1)
chan1 = client1.get_transport().open_session()
chan2 = client2.get_transport().open_session()
#chan3 = client3.get_transport().open_session()
time.sleep(1)
chan1.exec_command(f"sudo killall pigpiod")
chan2.exec_command(f"sudo killall pigpiod")
#chan3.exec_command(f"sudo killall pigpiod")
time.sleep(1)
chan1 = client1.get_transport().open_session()
chan2 = client2.get_transport().open_session()
#chan3 = client3.get_transport().open_session()
chan1.exec_command(f"sudo pigpiod -n 192.168.137.1")
chan2.exec_command(f"sudo pigpiod -n 192.168.137.1")
#chan3.exec_command(f"sudo pigpiod -n 192.168.137.1")

client1.close()
client2.close()
#client3.close()