import paramiko
import time

client1 = paramiko.SSHClient()
client1.set_missing_host_key_policy(paramiko.WarningPolicy())
client1.set_missing_host_key_policy(paramiko.AutoAddPolicy())
client2 = paramiko.SSHClient()
client2.set_missing_host_key_policy(paramiko.WarningPolicy())
client2.set_missing_host_key_policy(paramiko.AutoAddPolicy())
#client3 = paramiko.SSHClient()
#client3.set_missing_host_key_policy(paramiko.WarningPolicy())
#client3.set_missing_host_key_policy(paramiko.AutoAddPolicy())
time.sleep(1)
client1.connect("<IP ADDRESS DEVICE 1>", username='<USERNAME>', password="<PASSWORD>")
client2.connect("<IP ADDRESS DEVICE 2>", username='<USERNAME>', password="<PASSWORD>") # change back to 3 ---------------------
#client3.connect("<IP ADDRESS DEVICE 3>", username='<USERNAME>', password="<PASSWORD>")
time.sleep(1)
chan1 = client1.get_transport().open_session()
chan2 = client2.get_transport().open_session()
#chan3 = client3.get_transport().open_session()
time.sleep(1)
chan1.exec_command(f"sudo killall pigpiod")
chan2.exec_command(f"sudo killall pigpiod")
#chan3.exec_command(f"sudo killall pigpiod")
time.sleep(1)
chan1 = client1.get_transport().open_session()
chan2 = client2.get_transport().open_session()
#chan3 = client3.get_transport().open_session()
chan1.exec_command(f"sudo pigpiod -n <IP ADDRESS MASTER>")
chan2.exec_command(f"sudo pigpiod -n <IP ADDRESS MASTER>")
#chan3.exec_command(f"sudo pigpiod -n <IP ADDRESS MASTER>")

client1.close()
client2.close()
#client3.close()